services:
  attempt:
    build: 
      context: .
      dockerfile: ./apps/attempt/Dockerfile
      target: development
    command: npm run start:dev attempt
    env_file:
      - ./apps/attempt/.env
    depends_on:
      - mongo
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'

  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/usr/src/app
    ports:
      - '3001:3001'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
